name: Setup Terraform
description: Install a specific version of Terraform

inputs:
  terraform-version:
    description: Terraform version to install
    required: false
    default: "1.6.6"

dependencyTemplates:
  - name: terraform
    installMethod: binary-download
    checkBinary: terraform
    binaryDownload:
      url: https://releases.hashicorp.com/terraform/${{ inputs.terraform-version }}/terraform_${{ inputs.terraform-version }}_linux_$ARCH.zip
      archiveFormat: zip
      binaryPath: terraform
      installPath: /usr/local/bin
      executableName: terraform

instructions: []
